TFG: change method of submiting checkbox submission

diff --git a/Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test b/Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test
--- a/Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test
+++ b/Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test
@@ -2,8 +2,37 @@ echo "Starting Test"
 PYTHONUNBUFFERED=1 checkbox-cli control "$DEVICE_IP" checkbox-launcher
 EXITCODE=$?
 echo CHECKBOX EXITCODE: "$EXITCODE"
-echo "Copy submission tar file to artifacts folder"
-mv /home/ubuntu/c3-local-submission.tar.xz artifacts/
+
+SESSION_DESC="CE-QA-PC_Test"
+FILE_PATH="/home/ubuntu/c3-local-submission.tar.xz"
+MAXLOOP=20
+COUNT=0
+
+# Check if the file exists
+if [ ! -f "$FILE_PATH" ]; then
+    echo "Submission tar file not found: $FILE_PATH"
+    exit 1
+fi
+
+while [ $COUNT -lt $MAXLOOP ]; do
+    RET=$(checkbox-cli submit -m "$SESSION_DESC" "$HEXR_DEVICE_SECURE_ID" "$FILE_PATH")
+    if [[ $RET == *"Successfully"* ]]; then
+        echo "Found 'Successfully' in output."
+        echo "$RET" > "artifacts/submission_url.log"
+        break
+    else
+        echo "Attempt $((COUNT+1)): 'Successfully' not found."
+    fi
+    COUNT=$((COUNT+1))
+done
+
+if [ $COUNT -ge $MAXLOOP ]; then
+    echo "Maximum attempts reached without success."
+    exit 1
+fi
+
+echo "Move submission tar file to artifacts folder"
+mv "$FILE_PATH" artifacts/
 echo "Files in artifacts:"
 ls artifacts
 
